on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        make install
    - name: Pylint
      run: |
        make lint
    - name: Formatting
      run: |
        make format
    - name: Build Container
      run: |
        make build
    - name: Run Container
      run: |
        make run
